### ISSUE TITLE
[FEATURE]GitHub Actionsでself-assignを可能にする

### ISSUE THREAD

**Issue by nishio** [digitaldemocracy2030/kouchou-ai#95]
# 背景

GitHubのOSSプロジェクトで、コントリビューターが自分でIssueをself-assignできるようにするには、コントリビューターが最低でも **「Triage」（トリアージ）権限** を持っている必要があるが、個別につけて回るのは大変である。そこでGitHub Actionsでそれを可能にする。

# 提案内容
(by GPT4.5)

GitHubのOSSプロジェクトで、コントリビューターが自分でIssueをself-assignできるようにするには、以下の手順が必要です。

### 方法1: コラボレーターとして追加する（推奨）

1. リポジトリのSettings → Collaborators（共同作業者）を開く。
2. コントリビューターを追加し、権限を`Triage`に設定する。

この方法は明示的でわかりやすいですが、外部からの参加者が多数いる場合には面倒です。

### 方法2: GitHub ActionsなどでBotを使う（推奨）

- OSSのコミュニティでよく使われる方法です。
- Issueに特定のコメント（例：`/assign`）をすると、自動的に自分自身をアサインできるようにします。

代表的なアクション例：

- [[actions-ecosystem/action-assign-yourself](https://github.com/actions-ecosystem/action-assign-yourself)](https://github.com/actions-ecosystem/action-assign-yourself)

設定例 (`.github/workflows/assign-yourself.yml`)：
```yaml
name: Assign yourself

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions-ecosystem/action-assign-yourself@v1
        with:
          trigger: '/assign'
```

コメント欄でユーザーが`/assign`と打つだけで、Issueが自動で割り当てられます。

---

### 推奨される方法：

- **外部コントリビューターが多いOSSでは方法2（GitHub Actions）をおすすめします。**
- 管理が容易で、自動化され、権限設定を手動で管理する必要がありません。

以上が、GitHubのOSSプロジェクトでself-assignを可能にする一般的な方法です。
